### ISSUE TITLE
Smart indexation

### ISSUE THREAD

**Issue by rnmp** [lucuma/Clay#2]
Let's suppose that we have this:

```python
views/
    index.html
    index/
        page1.html
        page2.html
```

It would be awesome if somehow the `index.html` file could retrieve all of the `index/` children info such as paths and even retrieve Jinja2 blocks like title, or whatever. That would be awesome for blogs, listing of products, etc.

**Comment by jpscaletti** [comment]
The last commit (omg finally) add this functionality

```jinja
{{ toc.index() }}
```

renders to

```html
<ul class="toc">
    <li><a href="/index.html">index.html</a></li>
    <li><a href="/index.html">page1.html</a></li>
    <li><a href="/index.html">page2.html</a></li>
</ul>
```

See https://github.com/lucuma/Clay/blob/master/clay/tglobals.py#L41
