### ISSUE TITLE
How to use webassets with Clay?

### ISSUE THREAD

**Issue by kemar** [lucuma/Clay#24]
Hi,

I'm struggling to find a way to add the [webassets extension to Jinja2](http://webassets.readthedocs.io/en/latest/integration/jinja2.html) with Clay.

Your basic template has [a reference to it here](https://github.com/lucuma/clay-template/blob/a08cde090fdb6158d71a6da82064b6c32ba49ccc/settings.py#L10-L11).

What would be the best way to do it, do you have an exemple?

Thank you very much.

**Comment by jpscaletti** [comment]
I'm sorry, there were many things that weren't working with this project. A clean rewrite is under way.
