### ISSUE TITLE
command not found: clay

### ISSUE THREAD

**Issue by motionharvest** [lucuma/clay#33]
There is not a lot online about clay. The project that I've been put on is using it, and I've run `pip install clay` yet when I try `clay new mysite` I see **command not found: clay**.

Where is clay located so I can add it to my system path?

**Comment by jpsca** [comment]
Clay (including the `clay` executable) is installed whenever the rest of your python packages are
In any case, you don't need to add anything to your system path. Please check if the installation finished without any error, or try to install it again.
